In [1]:
import numpy as np

In [2]:
Oned = np.array([2,3,4,5,6,6,7,7,7])
Twod = np.array([[1,2],[3,4] , [5,6]])
Threed = np.array([[[1,2,3],[4,5,6]] ,[[3,4,5],[5,6,7]]])
print(Oned)
print(Twod)
print(Threed)


[2 3 4 5 6 6 7 7 7]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]]


In [3]:
print(Threed.ndim)
print(Threed.shape)
print(Twod.size)

3
(2, 2, 3)
6


In [4]:
print(Oned[1:6])
print(Oned[::2])
print(Oned[::-1])

[3 4 5 6 6]
[2 4 6 7 7]
[7 7 7 6 6 5 4 3 2]


In [5]:
print(Twod[1,1])
print(Twod[1])
print(Twod[:,1])
print(Twod[1:3,0:2])

4
[3 4]
[2 4 6]
[[3 4]
 [5 6]]


In [6]:
print(Threed[0,1,2])

6


In [7]:
print(Twod[1:-1])

[[3 4]]


In [8]:
print(Oned[1:6])

[3 4 5 6 6]


In [9]:
print(Oned[4:])

[6 6 7 7 7]


In [10]:
print(Oned[:4])

[2 3 4 5]


In [11]:
print(Oned[-3:])

[7 7 7]


In [12]:
print(Oned[1:5:2])

[3 5]


In [13]:
print(Oned[::2])

[2 4 6 7 7]


In [14]:
print(Twod)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(Twod[1:,0:])


[[3 4]
 [5 6]]


In [16]:
print(Twod[0:1,1])

[2]


In [17]:
arr2d = np.array([[1,2,3] ,[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [18]:
print(arr2d[0:,1:])

[[2 3]
 [5 6]]


In [19]:
arr3d = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,8]],[[6,7,8,9],[1,22,3,4],[5,6,77,8]]])
print(arr3d)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9  8]]

 [[ 6  7  8  9]
  [ 1 22  3  4]
  [ 5  6 77  8]]]


In [20]:
print(arr3d[1,0:,0:])

[[ 6  7  8  9]
 [ 1 22  3  4]
 [ 5  6 77  8]]


In [21]:
print(arr3d[0,0,0:])

[1 2 3 4]


In [22]:
print(arr3d[0:,0:,3])

[[4 7 8]
 [9 4 8]]


In [23]:
print(arr3d[:,:,-1])

[[4 7 8]
 [9 4 8]]


In [24]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
for x in arr1d:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [26]:
for x in arr2d:
     print(x)

[1 2 3]
[4 5 6]


In [27]:
for x in arr2d:
    for y in x:
        print(y)

1
2
3
4
5
6


In [28]:
for x in arr3d:
    print(x)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 8]]
[[ 6  7  8  9]
 [ 1 22  3  4]
 [ 5  6 77  8]]


In [29]:
for x in arr3d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
4
5
6
7
7
8
9
8
6
7
8
9
1
22
3
4
5
6
77
8


In [30]:
for x in np.nditer(arr3d):
    print(x)

1
2
3
4
4
5
6
7
7
8
9
8
6
7
8
9
1
22
3
4
5
6
77
8


In [31]:
for x in np.nditer(arr3d[:,::2]):
    print(x)

1
2
3
4
7
8
9
8
6
7
8
9
5
6
77
8


In [32]:
print(arr1d.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [33]:
print(Oned.reshape(3,3))

[[2 3 4]
 [5 6 6]
 [7 7 7]]


In [34]:
txt = f"The price is {95:.2f} dollars"
print(txt)


The price is 95.00 dollars


In [35]:
arrj = np.concatenate((arr1d , Oned))
print(arrj)

[ 1  2  3  4  5  6  7  8  9 10 11 12  2  3  4  5  6  6  7  7  7]


In [36]:
np.shape(arr2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
mat = np.array([[1,2,4],[5,6,7]])
mat

array([[1, 2, 4],
       [5, 6, 7]])

In [38]:
arr5 = np.concatenate((arr2d , mat))
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 4],
       [5, 6, 7]])

In [39]:
arr5 = np.concatenate((arr2d , mat), axis = 1)
arr5

array([[1, 2, 3, 1, 2, 4],
       [4, 5, 6, 5, 6, 7]])

In [40]:
ar1 = np.array([])
print(np.stack((arr1d, Oned), axis = 1))


ValueError: all input arrays must have the same shape