In [1]:
import numpy as np

In [3]:
arr1d = np.array([1,2,3,4,5])
arr1 = np.array([7,8,9,0,6])
print(arr1d)
print(arr1)

[1 2 3 4 5]
[7 8 9 0 6]


In [9]:
print(np.stack((arr1d,arr1), axis=1))

[[1 7]
 [2 8]
 [3 9]
 [4 0]
 [5 6]]


In [11]:
print(np.hstack((arr1d, arr1)))

[1 2 3 4 5 7 8 9 0 6]


In [12]:
print(np.dstack((arr1d, arr1)))

[[[1 7]
  [2 8]
  [3 9]
  [4 0]
  [5 6]]]


In [14]:
print(np.array_split(arr1d,2))

[array([1, 2, 3]), array([4, 5])]


In [15]:
newarray = np.array_split(arr1d, 2)
print(newarray[0])

[1 2 3]


In [20]:
arr2d = np.array([[1,2,3],[4,5,6],[5,6,7],[8,9,11]])
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 11]]


In [27]:
print(np.array_split(arr2d,2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 5,  6,  7],
       [ 8,  9, 11]])]


In [23]:
narr =np.array_split(arr2d,2)
print(narr[0][1])

[4 5 6]


In [29]:
print(np.where(arr1d%2==0))

(array([1, 3]),)


In [35]:
print(np.searchsorted(arr1d, 1, side='right'))

1


In [36]:
print(np.sort(arr1d))

[1 2 3 4 5]


In [5]:
arr5 = np.arange(0,35).reshape(7,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [11]:
arr3d = np.arange(1,13).reshape(2,2,3)
arr3 = np.arange(13,25).reshape(2,2,3)
print(arr3d)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


In [13]:
print(np.concatenate((arr3d,arr3 ),axis = 1))

[[[ 1  2  3]
  [ 4  5  6]
  [13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]
  [19 20 21]
  [22 23 24]]]


In [ ]:
print(np.sum((arr3d,arr3), axis=0))

[[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]]


In [17]:
print(np.sum((arr3d, arr3), axis= 1))

[[[ 8 10 12]
  [14 16 18]]

 [[32 34 36]
  [38 40 42]]]


In [18]:
print(np.sum((arr3d,arr3),axis=2))

[[[ 5  7  9]
  [17 19 21]]

 [[29 31 33]
  [41 43 45]]]


In [22]:
np.stack((arr3d,arr3))

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [23]:
np.vstack((arr3d,arr3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [28]:
arr3d[:] >5

array([[[False, False, False],
        [False, False,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [37]:
arr2d = np.arange(1,7).reshape(2,3)
arr1d = np.array([1,2,3,4,6])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2d[: ,np.newaxis, :]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [35]:
print(np.shape(arr2d[:, np.newaxis]))

(2, 1, 3)


In [38]:
arr3[arr3>5]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])