In [118]:
import pandas as pd
import numpy as np

In [119]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [120]:
df = pd.read_csv('1.04. Real-life example.csv')
df.head(5)

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4


In [121]:
df.isna().sum()

Brand             0
Price           172
Body              0
Mileage           0
EngineV         150
Engine Type       0
Registration      0
Year              0
Model             0
dtype: int64

In [122]:
df.size

39105

In [123]:
df.shape

(4345, 9)

In [124]:
df.dropna()

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4
...,...,...,...,...,...,...,...,...,...
4339,Toyota,17900.0,sedan,35,1.6,Petrol,yes,2014,Corolla
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520


In [125]:
df.replace([' ' , '?' , 'na' , 'nil'], np.nan)

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4
...,...,...,...,...,...,...,...,...,...
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520
4343,Toyota,14200.0,sedan,31,NaN,Petrol,yes,2014,Corolla


In [126]:
df.Brand.unique()

array(['BMW', 'Mercedes-Benz', 'Audi', 'Toyota', 'Renault', 'Volkswagen',
       'Mitsubishi'], dtype=object)

In [127]:
df.dropna(inplace = True)

In [128]:
df

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4
...,...,...,...,...,...,...,...,...,...
4339,Toyota,17900.0,sedan,35,1.6,Petrol,yes,2014,Corolla
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520


In [129]:
print(df.Brand.value_counts())

Brand
Volkswagen       880
Mercedes-Benz    823
BMW              640
Toyota           510
Renault          445
Audi             420
Mitsubishi       307
Name: count, dtype: int64


In [130]:
scaler = MinMaxScaler()

In [131]:
df_nums = df.select_dtypes(include = ['number'])

In [132]:
print(scaler.fit(df_nums))

MinMaxScaler()


In [133]:
print(scaler.transform(df_nums))

[[0.01202405 0.28265306 0.01408592 0.46808511]
 [0.0243821  0.43571429 0.02314116 0.63829787]
 [0.04241817 0.36530612 0.04427005 0.72340426]
 ...
 [0.01970608 0.00102041 0.02917799 0.63829787]
 [0.0247161  0.19795918 0.01408592 0.34042553]
 [0.04308617 0.12653061 0.01408592 0.93617021]]


In [134]:
from sklearn.model_selection import train_test_split

In [135]:
from sklearn.preprocessing import Normalizer

In [136]:
norm = Normalizer(norm = 'l2')

In [137]:
print(norm.fit(df_nums))

Normalizer()


In [138]:
print(norm.transform(df_nums))

[[9.02010304e-01 5.94897272e-02 4.29528716e-04 4.27595837e-01]
 [9.68117348e-01 5.23273554e-02 3.55384849e-04 2.44970453e-01]
 [9.88498757e-01 2.66077109e-02 3.71616074e-04 1.48869399e-01]
 ...
 [9.55820195e-01 1.47049261e-04 5.14672413e-04 2.93951472e-01]
 [9.70300437e-01 2.35297856e-02 2.42575109e-04 2.40755796e-01]
 [9.89024129e-01 9.08436978e-03 1.46522093e-04 1.47474487e-01]]


In [139]:
df_nums

,Price,Mileage,EngineV,Year
0,4200.0,277,2.0,1991
1,7900.0,427,2.9,1999
2,13300.0,358,5.0,2003
3,23000.0,240,4.2,2007
4,18300.0,120,2.0,2011
...,...,...,...,...
4339,17900.0,35,1.6,2014
4340,125000.0,9,3.0,2014
4341,6500.0,1,3.5,1999
4342,8000.0,194,2.0,1985


In [140]:
X =df_nums.drop('Mileage' , axis = 1)
y = df_nums.iloc[:,1]

In [141]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size= 0.2 , random_state= 12)


In [142]:
X_train


,Price,EngineV,Year
1339,2650.0,2.0,2000
2012,8200.0,1.6,2010
3603,7750.0,1.9,2002
3264,12500.0,5.0,2002
2183,6900.0,2.4,1999
...,...,...,...
3582,7200.0,1.6,2007
3595,20900.0,2.5,2013
1528,9200.0,1.6,2007
1833,25500.0,4.8,2007


In [143]:
X_test

,Price,EngineV,Year
729,4000.0,1.9,2005
4201,13900.0,3.0,2002
481,21500.0,2.0,2007
4084,15300.0,2.2,2008
1583,7300.0,2.8,1998
...,...,...,...
1499,2900.0,1.6,2000
3546,19400.0,2.0,2011
1316,4200.0,1.9,2007
198,20500.0,2.0,2011


In [144]:
y_train

1339    335
2012    180
3603    265
3264    230
2183    250
       ... 
3582    159
3595     18
1528    127
1833    187
2018    270
Name: Mileage, Length: 3220, dtype: int64

In [145]:


y_test

729     215
4201     80
481     135
4084    234
1583    245
       ... 
1499    230
3546     88
1316    142
198      73
3598     47
Name: Mileage, Length: 805, dtype: int64

In [146]:
scale = StandardScaler()

In [147]:
print(scale.fit(X_train))

StandardScaler()


In [148]:
print(scale.mean_)

[1.96722834e+04 2.75201863e+00 2.00639845e+03]


In [149]:
print(scale.transform(X_train))

[[-0.66057916 -0.15188298 -0.94982814]
 [-0.4452018  -0.2326698   0.5346385 ]
 [-0.46266483 -0.17207969 -0.65293481]
 ...
 [-0.40639507 -0.2326698   0.08929851]
 [ 0.22615463  0.41362475  0.08929851]
 [-0.48400853 -0.17207969  0.23774517]]


In [150]:
X_test_scaled = scale.transform(X_test)

In [151]:
X_test_scaled

array([[-0.60819007, -0.17207969, -0.20759482],
       [-0.22400344,  0.05008406, -0.65293481],
       [ 0.07092771, -0.15188298,  0.08929851],
       ...,
       [-0.60042873, -0.17207969,  0.08929851],
       [ 0.03212098, -0.15188298,  0.68308516],
       [-0.49565055, -0.27306321,  0.83153182]], shape=(805, 3))

In [152]:
pd.get_dummies(df , columns=['Engine Type'])

,Brand,Price,Body,Mileage,EngineV,Registration,Year,Model,Engine Type_Diesel,Engine Type_Gas,Engine Type_Other,Engine Type_Petrol
0,BMW,4200.0,sedan,277,2.0,yes,1991,320,False,False,False,True
1,Mercedes-Benz,7900.0,van,427,2.9,yes,1999,Sprinter 212,True,False,False,False
2,Mercedes-Benz,13300.0,sedan,358,5.0,yes,2003,S 500,False,True,False,False
3,Audi,23000.0,crossover,240,4.2,yes,2007,Q7,False,False,False,True
4,Toyota,18300.0,crossover,120,2.0,yes,2011,Rav 4,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
4339,Toyota,17900.0,sedan,35,1.6,yes,2014,Corolla,False,False,False,True
4340,Mercedes-Benz,125000.0,sedan,9,3.0,yes,2014,S 350,True,False,False,False
4341,BMW,6500.0,sedan,1,3.5,yes,1999,535,False,False,False,True
4342,BMW,8000.0,sedan,194,2.0,yes,1985,520,False,False,False,True


In [153]:
pd.get_dummies(df , columns=['Engine Type'] , drop_first= True)

,Brand,Price,Body,Mileage,EngineV,Registration,Year,Model,Engine Type_Gas,Engine Type_Other,Engine Type_Petrol
0,BMW,4200.0,sedan,277,2.0,yes,1991,320,False,False,True
1,Mercedes-Benz,7900.0,van,427,2.9,yes,1999,Sprinter 212,False,False,False
2,Mercedes-Benz,13300.0,sedan,358,5.0,yes,2003,S 500,True,False,False
3,Audi,23000.0,crossover,240,4.2,yes,2007,Q7,False,False,True
4,Toyota,18300.0,crossover,120,2.0,yes,2011,Rav 4,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
4339,Toyota,17900.0,sedan,35,1.6,yes,2014,Corolla,False,False,True
4340,Mercedes-Benz,125000.0,sedan,9,3.0,yes,2014,S 350,False,False,False
4341,BMW,6500.0,sedan,1,3.5,yes,1999,535,False,False,True
4342,BMW,8000.0,sedan,194,2.0,yes,1985,520,False,False,True


In [160]:
df.reset_index(inplace=True)

In [161]:
from sklearn.preprocessing import OneHotEncoder

In [162]:
encoder = OneHotEncoder(sparse_output=False , drop='first')

In [163]:
encoded = encoder.fit_transform(df[['Engine Type']])

In [164]:
encoded

array([[0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.]], shape=(4025, 3))

In [165]:
df_encoded = pd.DataFrame(encoded , columns=encoder.get_feature_names_out(['Engine Type']))

In [166]:
df_encoded

,Engine Type_Gas,Engine Type_Other,Engine Type_Petrol
0,0.0,0.0,1.0
1,0.0,0.0,0.0
2,1.0,0.0,0.0
3,0.0,0.0,1.0
4,0.0,0.0,1.0
...,...,...,...
4020,0.0,0.0,1.0
4021,0.0,0.0,0.0
4022,0.0,0.0,1.0
4023,0.0,0.0,1.0


In [168]:
df_concat = pd.concat([df,df_encoded] , axis=1)

In [169]:
df_concat

,index,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model,Engine Type_Gas,Engine Type_Other,Engine Type_Petrol
0,0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320,0.0,0.0,1.0
1,1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212,0.0,0.0,0.0
2,2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500,1.0,0.0,0.0
3,3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7,0.0,0.0,1.0
4,4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4020,4339,Toyota,17900.0,sedan,35,1.6,Petrol,yes,2014,Corolla,0.0,0.0,1.0
4021,4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350,0.0,0.0,0.0
4022,4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535,0.0,0.0,1.0
4023,4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520,0.0,0.0,1.0
